version: "3"

services:
  namenode:
    container_name: namenode
    image: hadoop-namenode:3.0.0-hadoop3.2.0-java8
    #image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    volumes:
      - /opt/helios/hadoop/namenode:/hadoop/dfs/name:rw
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    ports:
      - "9870:9870"
  datanode:
    container_name: datanode
    image: hadoop-datanode:3.0.0-hadoop3.2.0-java8
    #image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    volumes:
      - /opt/helios/hadoop/datanode:/hadoop/dfs/data:rw
    env_file:
      - ./hadoop.env
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    ports:
      - "9864:9864"
  hive-server:
    container_name: hive-server
    image: hive-base:2.3.2-postgresql
    volumes:
      - /opt/helios/hive/log:/opt/helios/hive/log:rw
    env_file:
      - ./hadoop-hive.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    ports:
      - "10000:10000"
      - "10002:10002"
  hive-metastore:
    container_name: hive-metastore
    image: hive-base:2.3.2-postgresql
    env_file:
      - ./hadoop-hive.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864 hive-metastore-postgresql:5432"
    ports:
      - "9083:9083"
  hive-metastore-postgresql:
    container_name: hive-metastore-postgresql
    image: hive-metastore-postgresql:2.3.0

volumes:
  namenode:
  datanode:
