version: "3"

services:
  hadoop-base:
    build:
      context: ./hadoop-base
      dockerfile: Dockerfile
    image: hadoop-base:2.0.0-hadoop2.7.4-java8
  hadoop-namenode:
    build:
      context: ./hadoop-namenode
      dockerfile: Dockerfile
    image: hadoop-namenode:2.0.0-hadoop2.7.4-java8
  hadoop-datanode:
    build:
      context: ./hadoop-datanode
      dockerfile: Dockerfile
    image: hadoop-datanode:2.0.0-hadoop2.7.4-java8
  hive-metastore-postgresql:
    build:
      context: ./hive-metastore-postgresql
      dockerfile: Dockerfile
    image: hive-metastore-postgresql:2.3.0
  hive-base:
    build:
      context: ./hive-base
      dockerfile: Dockerfile
    image: hive-base:2.3.2-postgresql
    depends_on:
      - hadoop-base
